steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/cloudbuild-demo-barbacoa/whats-the-word/whats-the-word', 'app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/cloudbuild-demo-barbacoa/whats-the-word/whats-the-word']