# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
kind: Namespace
apiVersion: v1
metadata:
  name: whats-the-word
  labels:
    name: whats-the-word
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: whats-the-word
  labels:
    app: whats-the-word
  namespace: whats-the-word
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: whats-the-word
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whats-the-word
  namespace: whats-the-word
  labels:
    app: whats-the-word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whats-the-word
  template:
    metadata:
      labels:
        app: whats-the-word
    spec:
      containers:
        - name: whats-the-word
          image: whats-the-word
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
      terminationGracePeriodSeconds: 1

